name: OpenAPI Publisher

on:
  push:
    branches:
      - main

jobs:
  validate:
    uses: ./.github/workflows/validate-openapi.yaml
  publish:
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Check out repository

      - uses: readmeio/rdme@7.5.0
        name: Sync Open Payments API spec
        with:
          rdme: openapi resource-server.yaml --workingDirectory=openapi --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_OP_API_ID }}

      - uses: readmeio/rdme@7.5.0
        name: Sync Auth Server API spec
        with:
          rdme: openapi auth-server.yaml --workingDirectory=openapi --key=${{ secrets.README_API_KEY }} --id=${{ secrets.README_AUTH_API_ID }}
